### PR TITLE
Add new caller SVIM

### PR DESCRIPTION
**Pull request by eldariont**
This is a work in progress to add my SV caller SVIM to nano-snakemake.

### CODE REVIEW

**Comment by wdecoster** [comment]
Thanks for contributing! Let me know when you consider this ready for merging.
I'm also making some changes to this workflow this week, as I plan to reimplement how I deal with high confidence and high sensitivity variant sets, as well as adding other variant callers.

**Comment by eldariont** [comment]
Cool, I'll let you know :)

FYI, here is the length distribution when filtering SVIM calls with a threshold of 40:
sv-length_svim_genotypes_err2631600

There were a few problems that I faced when adding SVIM to nano-snakemake:
- `SV-length-plot.py` removes my INV calls because their SVLEN is undefined. But according to the VCF specs, inversions don't have an SVLEN (because ALT and REF alleles are of the same length). Maybe we can compute SV length from END-POS for inversions?
- `scripts/SV-carriers-plot.py` looks at genotypes which SVIM does not output. Therefore, `SV-svim_carriers.png` is a bit useless for SVIM
- `precision-recall-curve-qualities.py` crashes on my SVIM output with `KeyError: b'QV'`. Where does QV come from and how did you run it for your blog post? It would be nice to add the PR curve into the pipeline at some point, wouldn't it?

Cheers,
David

**Comment by wdecoster** [comment]
That length profile is looking as expected :-)

> SV-length-plot.py removes my INV calls because their SVLEN is undefined. But according to the VCF specs, inversions don't have an SVLEN (because ALT and REF alleles are of the same length). Maybe we can compute SV length from END-POS for inversions?

That wouls be okay yes. Implementing this in `SV-length-plot.py` wouldn't be too hard.

> scripts/SV-carriers-plot.py looks at genotypes which SVIM does not output. Therefore, SV-svim_carriers.png is a bit useless for SVIM

Then it should be possible to specify that this plot shouldn't be created for svim. IIRC it shows a barchart of the number of carriers per variant. It would nevertheless in a later stage be useful for svim to have genotypes...

> precision-recall-curve-qualities.py crashes on my SVIM output with KeyError: b'QV'. Where does QV come from and how did you run it for your blog post? It would be nice to add the PR curve into the pipeline at some point, wouldn't it?

QV comes from SURVIVOR, which I use to combine SV vcf files, in this case the SVIM vcf with a truth set I use. I've also seen truvari frequently, which I'd expect to do roughly the same. Adding the PR curve into the pipeline only makes sense if you have a truth set, no?

**Comment by wdecoster** [comment]
I think it should be okay to directly output variants to `{aligner}/svim_genotypes` and remove the `copy_svim` rule, or did you encounter errors when doing that?

**Comment by wdecoster** [comment]
Presumably unintentionally you added long paths for sniffles: `/scratch/ngsvin/bin/SVcalling/Sniffles/Sniffles-1.0.10/bin/sniffles-core-1.0.10`, which will have to be removed before merging (but you can leave them as such for your testing of course).

**Comment by eldariont** [comment]
> That wouls be okay yes. Implementing this in `SV-length-plot.py` wouldn't be too hard.

Did this in 1b4a601.

> Then it should be possible to specify that this plot shouldn't be created for svim. IIRC it shows a barchart of the number of carriers per variant. It would nevertheless in a later stage be useful for svim to have genotypes...

Did this in 4eed7aa.

> I think it should be okay to directly output variants to `{aligner}/svim_genotypes` and remove the `copy_svim` rule, or did you encounter errors when doing that?

Yes, I added the copy rule as a placeholder for a genotyping step yet to come. But right now we can get rid of it -> a933ad8

>  QV comes from SURVIVOR, which I use to combine SV vcf files, in this case the SVIM vcf with a truth set I use. I've also seen truvari frequently, which I'd expect to do roughly the same. Adding the PR curve into the pipeline only makes sense if you have a truth set, no?

Well, you are right. You would need a truth set but the user could set it in a config file. Unfortunately, I still cannot get the script to run on the SVIM output and a truth set. I got around the KeyError by updating SURVIVOR but it seems as if the script needs genotypes. Did you do any post-processing on the SVIM output? And did you run the script on an individual sample or the combined vcf?

**Comment by wdecoster** [comment]
Ow yes, I did add dummy genotypes using the script below. I should have said that earlier, sorry for the confusion. Since zygosity is not taken into account by my precision-recall evaluation I just assumed each variant is heterozygous.

```
import sys

for line in open(sys.argv[1]):
    if line.startswith('##'):
        print(line, end="")
    elif line.startswith('#'):
        print("""##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">""")
        print("{}\t{}\t{}".format(line.strip(), "FORMAT", "NA19240"))
    else:
        print("{}\t{}\t{}".format(line.strip(), "GT", "0/1"))
```

> You would need a truth set but the user could set it in a config file.

Comparing against a truth set is useful for evaluation, but for me that's not the main purpose of this workflow. I'd use it for samples for which I do not have a truth set and I'm exploring SVs.

**Comment by eldariont** [comment]
Cool, thanks!

> Comparing against a truth set is useful for evaluation, but for me that's not the main purpose of this workflow. I'd use it for samples for which I do not have a truth set and I'm exploring SVs.

Yes, I understand. At the moment, I'm more interested in evaluating SVIM and the other tools so I might extend the pipeline in that direction in my fork of the repo. As far as I'm concerned you can merge this pull request now :)

**Comment by wdecoster** [comment]
I'll look into merging tomorrow - pushing my changes revealed some conflicts but I don't foresee real troubles here.

**Comment by eldariont** [comment]
Sure, take your time. And feel free to squash my 5 commits into 1 when merging.

**Comment by wdecoster** [comment]
I think I resolved the conflicts. Thanks for contributing!

**Comment by wdecoster** [comment]
I also added parameter settings for minimap2 alignment prior to pbsv variant calling. You may want to see if svim performs reasonably with those settings.

**Comment by eldariont** [comment]
Cool, thanks for merging! And for including pbsv! I will look into the new parameter settings.

**Pull request merged**
